Resources:
  ScoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "userId"
          "AttributeType": "S"
        - "AttributeName": "dateTime"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "userId"
          "KeyType": "HASH"
        - "AttributeName": "dateTime"
          "KeyType": "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "Scores"